/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsShowRouteImport } from './routes/requests/show'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsShowRoute = RequestsShowRouteImport.update({
  id: '/requests/show',
  path: '/requests/show',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tokens': typeof TokensRoute
  '/requests/show': typeof RequestsShowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tokens': typeof TokensRoute
  '/requests/show': typeof RequestsShowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tokens': typeof TokensRoute
  '/requests/show': typeof RequestsShowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tokens' | '/requests/show'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tokens' | '/requests/show'
  id: '__root__' | '/' | '/tokens' | '/requests/show'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TokensRoute: typeof TokensRoute
  RequestsShowRoute: typeof RequestsShowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/show': {
      id: '/requests/show'
      path: '/requests/show'
      fullPath: '/requests/show'
      preLoaderRoute: typeof RequestsShowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TokensRoute: TokensRoute,
  RequestsShowRoute: RequestsShowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
